
version: 2.1
jobs:
  wibu:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "wibu hello"
          command: "echo Hello, Wibu!"

workflows:
  wibu-workflow:
    jobs:
      - wibu
